services:
  mktournament.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8080:80
    volumes:
      - ${HOME}/.aspnet/dev-certs/https:/root/.aspnet/https:ro
