//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MKTournament.Domain.Players {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlayerErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlayerErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MKTournament.Domain.Players.Errors.PlayerErrorMessages", typeof(PlayerErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PlayerEmail_AlreadyConfirmed {
            get {
                return ResourceManager.GetString("PlayerEmail_AlreadyConfirmed", resourceCulture);
            }
        }
        
        internal static string Player_NotRegistered {
            get {
                return ResourceManager.GetString("Player_NotRegistered", resourceCulture);
            }
        }
        
        internal static string PlayerRegitrationToken_NotMatch {
            get {
                return ResourceManager.GetString("PlayerRegitrationToken_NotMatch", resourceCulture);
            }
        }
        
        internal static string PlayerEmail_AlreadyTaken {
            get {
                return ResourceManager.GetString("PlayerEmail_AlreadyTaken", resourceCulture);
            }
        }
        
        internal static string PlayerNickName_AlreadyTaken {
            get {
                return ResourceManager.GetString("PlayerNickName_AlreadyTaken", resourceCulture);
            }
        }
    }
}
